FROM registry.cn-hangzhou.aliyuncs.com/docker_zchang/sails_base:latest
RUN npm install -g pm2 --registry=https://registry.npm.taobao.org
WORKDIR /
ADD /package.json /package.json
COPY / /
RUN  npm install > /dev/null 2>&1
# CMD ["sails", "lift"]
CMD ["pm2-runtime", "/ecosystem.config.js"]